### ISSUE TITLE
Only works with Pytorch<=0.1.12

### ISSUE THREAD

**Issue by muuoyaar** [stanfordnlp/wge#1]
First of all, many thanks for all the work you put into making sure your work is reproducible! 🥇 

It seems that ever since [Pytorch==0.2.0](https://github.com/pytorch/pytorch/releases/tag/v0.2.0) it is assumed that `keepdim=False` for reduction functions such as tensor.sum(). This assumption breaks a bunch of the code here... so it may be wise to specify a version in the Readme.

**Comment by ezliu** [comment]
Thanks for pointing this out! I've fixed the README
