### ISSUE TITLE
missing methods in script_tools.py?

### ISSUE THREAD

**Issue by knudmt** [stanfordnlp/wge#15]
This may not be an actual issue...
line 7 in launch_jobs.py (in the root of wge directory) seems to reference methods that are not defined in script_tools.py. 

`from script_tools import bash_string, upload_code, create_worksheet, task_lists, \
    upload_demos`

however, upload_code, create_worksheet, and upload_demos are included. Either they were left out b/c its very specific to the university blah blah blah. but it would be useful to have more context.

**Comment by ppasupat** [comment]
Hi! These are functions specific to running code on [CodaLab](https://worksheets.codalab.org/). Not sure why they aren't included considering that other methods like `open_cl_file` in `script_tools.py` also refer to CodaLab. Let me add them.

**Comment by ppasupat** [comment]
The methods are now added.

**Comment by knudmt** [comment]
That is really awesome! BTW this project is so amazing. I have been playing with if for a week or so.
