### ISSUE TITLE
miniwob-demos.git is not public

### ISSUE THREAD

**Issue by khliu1238** [stanfordnlp/wge#2]
hi:

when trying to reproduce your work, this line failed:

`git clone https://github.com/stanfordnlp/miniwob-demos.git $REPO_DIR/third-party/miniwob-demos
export RL_DEMO_DIR=$REPO_DIR/third-party/miniwob-demos/`

after inspection it's not public available. Will you release it?

**Comment by ppasupat** [comment]
Oops, it's released under https://github.com/stanfordnlp/miniwob-plusplus-demos

**Comment by khliu1238** [comment]
these are miniwob++, I thought the command looks for miniwob?

**Comment by ppasupat** [comment]
That's the public name of the repository. Just do
```
git clone https://github.com/stanfordnlp/miniwob-plusplus-demos.git $REPO_DIR/third-party/miniwob-demos 
```

**Comment by khliu1238** [comment]
ok thanks.
