### ISSUE TITLE
error when running --task click-tab-2

### ISSUE THREAD

**Issue by cometta** [stanfordnlp/wge#7]
Loading demonstrations: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 32/32 [00:00<00:00, 78.51it/s]
Loading GloVe embeddings:  99%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ | 99323/100000 [00:05<00:00, 16902.70it/s]
No GPUs detected. Sticking with CPUs.
No checkpoint to reload. Initializing fresh.
Inducing programs: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 32/32 [00:03<00:00,  9.69it/s]
No uncommitted changes.
New TrainingRun created at: /folder/data/experiments/1_unnamed
Outer training loop:   0%|          | 0/50000 [00:00<?, ?it/s]ERROR:root:############################################################
ERROR:root:=== SOMETHING WRONG HAPPENED !!! === (Retry attempt 1 / 5)
Traceback (most recent call last):
  File "/folder/wge/episode_generator.py", line 62, in __call__
    seeds, record_screenshots)
  File "/folder/wge/episode_generator.py", line 93, in _get_episodes
    actions = policy.act(states, test_policy)
  File "/folder/wge/wob_policy.py", line 425, in act
    action_scores_batch = self.score_actions(states)
  File "/folder/wge/wob_policy.py", line 192, in score_actions
    states, force_dom_attn, force_type_values)
  File "/folder/wge/wob_policy.py", line 221, in _score_actions
    dom_embeds, dom_elems = self._dom_embeds(states)
  File "/folder/wge/wob_policy.py", line 502, in _dom_embeds
    dom_elems, aligned_dom_embeds)
  File "/Users/user/homebrew/anaconda3/envs/miniwob/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/folder/wge/miniwob/embeddings.py", line 406, in forward
    pixel_neighbor_embeds, allow_empty=True)
  File "/folder/gtd/ml/torch/seq_batch.py", line 174, in reduce_mean
    weights = mask / sums.expand(*mask.size())
RuntimeError: The expanded size of the tensor (9) must match the existing size (96) at non-singleton dimension 1. at /Users/soumith/minicondabuild3/conda-bld/pytorch_1518371252923/work/torch/lib/TH/generic/THTensor.c:309
ERROR:root:Will restart the environment and try again ...

**Comment by ezliu** [comment]
I think this is a duplicate of issue #4. Can you confirm that downgrading PyTorch solves this?

**Comment by cometta** [comment]
It is working. can close this ticket
